spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  application:
    name: spring.batch
  datasource:
    url: jdbc:postgresql://localhost:5432/learn-batch-one
    username: postgres
    password: simple123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format-sql: true
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect